### ISSUE TITLE
Change SHA1 hash checker to an MD5 hash checker for ISO

### ISSUE THREAD

**Issue by WhiteTPoison** [Brawlback-Team/brawlback-launcher#9]
The ISO is checked for a SHA1 hash in a known-good list. This is useful for Melee as they have a known list of good SHA1 hashes, however we have a list of MD5 hashes.

**Comment by blasphemetheus** [comment]
in src/main/ there's two files edited: changed the verifyIso fn to verifyIsoMD5 that compares to MD5 hashes.
The sha1 function (_verifyIsoSHA1) has some validation checks that read in an int from the raw bytes of the iso (looks like 8 bytes) and sees if it is equal to the number 2 and throws it away as invalid if that is not met (to prune wildly different invalid iso's early). I got rid of that so it's slower. Someone can figure out what the equivalent first 8 bytes should be to speed it up again (idk if it's going to be consistent across all valid versions of brawl ISOs).

I also added a couple valid brawl md5 hashes and some examples of other invalid hashes just so I could demo them on my machine and see if the UI still works. It does. The only change being that if a hash isn't listed in the set of known hashes, it will show up as Unknown instead of Invalid. 

Known invalid iso's of brawl should be added and listed as invalid.
